Fix ticket 402 - GwsFeatureReader (Join Feature Reader) doesn't always return entire feature set http://trac.osgeo.org/mapguide/ticket/402
If you use the Feature Service GetFeatures() API on a GwsFeatureReader you will get the following error on any call of the GetFeatures() API after the 1st one: 

Error: Invalid argument(s): 

[1] = "103825848" 

The feature reader ID was not found. 

The reason for the failure is that the feature reader ID used by the GwsFeatureReader was not being properly cached and the lookup to find it would always fail. The lookup only happens on the 2nd and later calls of the API as the 1st call is suppose to cache it.



git-svn-id: http://svn.osgeo.org/mapguide/trunk@2733 a442ad82-b40c-0410-ae44-e6d7bd6e4a36