Fix a build issue with Visual Studio 2008 SP1.
With VS2008 SP1 RichTextEngine.cpp would fail to compile with the following error:

C:\Program Files\Microsoft Visual Studio 9.0\VC\include\xxbind1(298) : warning C4091: 'static ' : ignored on left of 'std::tr1::_Ph<_Nx>' when no variable is declared
        with
        [
            _Nx=10
        ]
C:\Program Files\Microsoft Visual Studio 9.0\VC\include\xxbind1(298) : error C2143: syntax error : missing ';' before 'constant'
C:\Program Files\Microsoft Visual Studio 9.0\VC\include\xxbind1(298) : error C2059: syntax error : 'constant'

The problem was due to line 394 in atom.h:

#define _10 3

Seems like this #define is also used somewhere inside the VS headers...

Fixed the problem by renaming the #defines in atom.h.


git-svn-id: http://svn.osgeo.org/mapguide/trunk/MgDev@3274 a442ad82-b40c-0410-ae44-e6d7bd6e4a36