RFC 135: Support Visual Studio 2012 (part 1).
Submit on behalf of Andy Zhang.

This submission updated OEM, Server, Web-tier and Desktop to support Visual Studio 2012. Only 3 source files are changed besides the solution and project files. 
1) Oem/dbxml/xqilla/include/xqilla/framework/XPath2MemoryManager.hpp
Error: The signature of std::make_pair is changed. 
Solution: change the code that call make_pair. The detail can be found in http://connect.microsoft.com/VisualStudio/feedback/details/691756/std-make-pair-error-in-vc11

2) Common/Stylization/PolygonUtils.h
Error: Some std classes such std::greater are moved to a different file.
Solution: include the file. For example, in order to use std::greater, we need to include <functional> when using VS 2012.

3) Oem/dbxml/dbxml/src/dbxml/nodeStore/NsUpdate.cpp
Error: XqillaAllocator doesn’t has ‘==’ operator
Solution: Just add the operator ‘==’ to fix the error.

Almost all the output directories in project files are updated to include $(Configuration). It will make things easy if want to we add new configuration Debug(v100) and release(v100) which use platform toolset v100 later. The old VS2008 and VS2010 in Server, Web-tier and Common are removed or updated. But some OEM projects have separate folder to place project files. For example, xerces-all/XercesLib has folders VC10 which stores VC10 project files. I created new folder to put the VS2012 files for this kind of projects. 

The changes has been built on CentOS 5.5. No errors found. The unit tests has been run on Windows. There is a feature service unit test failed. The test succeeded after update FDO lib/dll to VS 2012.

Known issues:
1. The changes of CsMap VS2012 support are not submitted (it will be submitted early next week). Now we can apply the patch attached in http://trac.osgeo.org/csmap/ticket/161 for build.
2. Unit test TestFeatureService::TestCase_BenchmarkSqliteAggregateJoin failed because FDO is still VS 2010. It will succeed after FDO update to VS 2012.  

git-svn-id: http://svn.osgeo.org/mapguide/trunk@7625 a442ad82-b40c-0410-ae44-e6d7bd6e4a36